---
cloudflared_k8s_state: present
cloudflared_namespace: cloudflared
cloudflared_tunnel_name: ""
cloudflared_hostname: ""
cloudflared_token_file: "/etc/olympus/cloudflare-api-token"
cloudflared_account_id: ""   # set in group_vars
cloudflared_image: "cloudflare/cloudflared:latest"
cloudflared_replicas: 1
# Service to route traffic to (defaults to traefik)
cloudflared_upstream_service: "traefik.traefik.svc.cluster.local"
cloudflared_upstream_port: 80
