---
# onode-0314ac — k3s secondary (non-init) server node
# LAN IP: 192.168.253.20

k3s_primary: false
k3s_init: false

tailscale_hostname: onode-0314ac
ddclient_extra_fqdns:
  - onode-0314ac.nwlnexus.net
