---
# onode-0312ce — k3s secondary (non-init) server node
# LAN IP: 192.168.253.24

k3s_primary: false
k3s_init: false

tailscale_hostname: onode-0312ce
ddclient_extra_fqdns:
  - onode-0312ce.nwlnexus.net
