---
- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: brew_stat

- name: Install Homebrew
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  environment:
    NONINTERACTIVE: "1"
  when:
    - homebrew_state == "present"
    - not brew_stat.stat.exists

- name: Remove Homebrew
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
  environment:
    NONINTERACTIVE: "1"
  when:
    - homebrew_state == "absent"
    - brew_stat.stat.exists

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when:
    - homebrew_state == "present"
    - brew_stat.stat.exists

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: present
  when: homebrew_state == "present"

- name: Ensure Homebrew shellenv in ~/.zprofile
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    create: true
    mode: "0644"
  become: false
  when:
    - homebrew_state == "present"
    - ansible_system == "Darwin"
