---
- name: Ensure ansible-pull log directory exists
  ansible.builtin.file:
    path: "{{ ansible_pull_log_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ 'sudo' if ansible_os_family != 'Darwin' else 'admin' }}"
    mode: "0755"
  become: true
  when: ansible_pull_state == "present"

- name: ansible-pull — macOS (LaunchDaemon)
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: ansible-pull — Linux (crontab)
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != "Darwin"
