---
- name: Restart ddclient (Linux)
  ansible.builtin.systemd:
    name: ddclient
    state: restarted
  become: true
  when: ansible_os_family != 'Darwin'
  listen: restart ddclient

- name: Restart ddclient (macOS)
  ansible.builtin.command: brew services restart ddclient
  changed_when: true
  when: ansible_os_family == 'Darwin'
  listen: restart ddclient
